# Generated by Django 5.0.3 on 2024-04-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "employmentTypeID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "typeTitle",
                    models.CharField(max_length=100, verbose_name="চাকরির ধরন"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                ("jobTitleID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "jobTitle",
                    models.CharField(max_length=100, verbose_name="পদবীর নাম"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("organizationID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "organizationName",
                    models.CharField(max_length=100, verbose_name="প্রতিষ্ঠানের নাম"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryGrade",
            fields=[
                ("gradeID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gradeTitle",
                    models.CharField(max_length=100, verbose_name="বেতন স্কেল"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("sectionID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sectionName",
                    models.CharField(max_length=100, verbose_name="শাখার নাম"),
                ),
                (
                    "organizationID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employeeID", models.AutoField(primary_key=True, serialize=False)),
                ("employeeName", models.CharField(max_length=100, verbose_name="নাম")),
                (
                    "nationalID",
                    models.CharField(
                        max_length=20, verbose_name="জাতীয় পরিচয়পত্র নম্বর"
                    ),
                ),
                (
                    "employeeNo",
                    models.CharField(max_length=20, verbose_name="কর্মচারী নম্বর"),
                ),
                (
                    "memorialNo",
                    models.CharField(max_length=20, verbose_name="স্মারক নং"),
                ),
                ("dateOfBirth", models.DateField(verbose_name="জন্ম তারিখ")),
                ("joiningDate", models.DateField(verbose_name="যোগদানের তারিখ")),
                ("email", models.EmailField(max_length=100, verbose_name="ইমেইল")),
                (
                    "mobileNo",
                    models.CharField(max_length=20, verbose_name="মোবাইল নম্বর"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/", verbose_name="ফটো"
                    ),
                ),
                (
                    "gpfAccountNo",
                    models.CharField(max_length=20, verbose_name="জিপিএফ হিসাব নম্বর"),
                ),
                (
                    "basicSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="মূল বেতন"
                    ),
                ),
                (
                    "epfPercent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="ইপিএফ শতকরা"
                    ),
                ),
                (
                    "cpfPercent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="সিপিএফ শতকরা"
                    ),
                ),
                ("displayOrder", models.IntegerField(verbose_name="ডিসপ্লে অর্ডার")),
                (
                    "employmentStatus",
                    models.IntegerField(
                        choices=[
                            (1, "চাকরিজীবী"),
                            (2, "পিআরএল"),
                            (3, "অবসরপ্রাপ্ত"),
                            (0, "নিষ্ক্রিয়"),
                        ],
                        verbose_name="কর্মসংস্থানের অবস্থা",
                    ),
                ),
                (
                    "employmentTypeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employmenttype",
                        verbose_name="চাকরির ধরন",
                    ),
                ),
                (
                    "jobTitleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.jobtitle",
                        verbose_name="পদবী",
                    ),
                ),
                (
                    "organizationID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.organization",
                        verbose_name="প্রতিষ্ঠান",
                    ),
                ),
                (
                    "gradeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.salarygrade",
                        verbose_name="বেতন স্কেল",
                    ),
                ),
                (
                    "sectionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.section",
                        verbose_name="শাখা",
                    ),
                ),
            ],
        ),
    ]
