# Generated by Django 5.0.3 on 2024-04-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employmentTypeID",
        ),
        migrations.AddField(
            model_name="employee",
            name="employmentType",
            field=models.IntegerField(
                choices=[(1, "কর্মকর্তা"), (2, "কর্মচারী"), (3, "পি আর এল")],
                default=1,
                verbose_name="চাকরির ধরন",
            ),
        ),
        migrations.DeleteModel(
            name="EmploymentType",
        ),
    ]
