# Generated by Django 5.0.3 on 2024-04-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan_management", "0002_alter_loantype_description_loanattachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoanAttachment",
        ),
    ]
