# Generated by Django 5.0.3 on 2024-04-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_management", "0004_loanattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanattachment",
            name="title",
            field=models.CharField(
                default="Default Title", max_length=100, verbose_name="Title"
            ),
        ),
    ]
